# Generated by Django 5.0 on 2023-12-28 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birdType', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('profession', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('activeVolunteer', models.BooleanField()),
                ('contact', models.CharField(max_length=100)),
                ('comments', models.TextField()),
            ],
        ),
    ]
